import type { Metadata } from "next";
// The Google font download step fails in this environment due to blocked
// network requests. Use system fonts instead of downloading fonts.
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper"; // <-- import the wrapper


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
