on:
  push:
    branches: [main]
permissions: read-all
name: Deploy on push main branch
jobs:
  web-deploy:
    name: 🎉 Deploy to Web Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.alskamusik.com
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
